Feature/ct 2
itbgtk09/WebDad pull request #2
Opened 2021-04-07 16:34 UTC by itbgtk09

2021-04-07 19:33 UTC, DenisKalyanov requested changes

2021-04-07 19:33 UTC, DenisKalyanov commented on index.html
> +                        <span>Более 800 переездов</span>
<span>Более 800 переездов</span>

2021-04-07 19:33 UTC, DenisKalyanov commented on index.html
> +                        <span>Более 800 переездов</span>
<span>Более 800 переездов</span>

2021-04-07 19:33 UTC, DenisKalyanov commented on index.html
> +                        <span>Более 800 переездов</span>
Более 800 переездов

2021-04-07 19:33 UTC, DenisKalyanov commented on index.html
> +                <div class="mobile-man-photo">
Лишняя обёртка div

2021-04-07 19:33 UTC, DenisKalyanov commented on index.html
> +                        <div class="icon-item icon__truck">
Лишняя обёртка div во всех 3х блоках.

2021-04-07 19:33 UTC, DenisKalyanov commented on index.html
> +                <div><img src="assets/section-header/phone.svg" alt=""></div>
Лишняя обёртка div

2021-04-07 19:33 UTC, DenisKalyanov commented on index.html
> +        <main class="content">
тег <main> предназначен для основного содержимого документа. Он не может быть вложен в section

2021-04-07 19:33 UTC, DenisKalyanov commented on css/style.css
> +  text-transform: uppercase;
Может сразу написать заглавными буквами? 
uppercase больше используется для логических преобразований, например когда с backend нам приходит текст и мы не знаем какой он, а отобразить нужно в uppercase, тогда мы используем его.

2021-04-07 19:33 UTC, DenisKalyanov commented on css/style.css
> +  margin: 0 3rem 0 0;
margin-right
Не принципиально, но лучше для понимания, и ещё эти нули каждый раз писать.

2021-04-07 19:33 UTC, DenisKalyanov commented on css/style.css
> +  padding: 24px;
Ну если уже везде решили использовать rem, то не будем делать этот блок исключением)

2021-04-07 20:14 UTC, itbgtk09 commented on index.html
> +                <span></span>
Чтобы нарисовать burger-menu, через span и span::before, span::after

2021-04-07 21:06 UTC, itbgtk09 commented on index.html
> +                <div><img src="assets/section-header/phone.svg" alt=""></div>
Здесь мысль такая: у тега <a> bgc с opacity 0.3, а у div 0.8, при наведении меняется bgc на op 1.

2021-04-08 08:03 UTC, DenisKalyanov commented on index.html
> +                <span></span>
> Чтобы нарисовать burger-menu, через span и span::before, span::after

А div:before, что уже не сработает?)

2021-04-08 10:01 UTC, DenisKalyanov commented on index.html
> +                <div><img src="assets/section-header/phone.svg" alt=""></div>
Сделай `div`, внутри которого `a` width:80%.
Этому `a` через ::before навесь значек вызова. и при ховере сделай его ширину 100% и плавность перехода 0.5

2021-04-08 10:50 UTC, itbgtk09 commented on index.html
> +                <span></span>
картинку через before добавить ? Или рисовать линии через before и after

2021-04-08 10:53 UTC, itbgtk09 commented on index.html
> +                <div class="mobile-man-photo">
этот div чтобы выровнять по вертикали и развести элементы по сторонам(display: flex;justify-content: space-between;align-items: flex-end;), в section.content .title-block(блок, который слева) и кнопку с телефоном, и

2021-04-09 11:44 UTC, DenisKalyanov approved these changes

2021-04-09 11:55 UTC, merged