Feature/ct 5
itbgtk09/WebDad pull request #6
Opened 2021-04-20 16:56 UTC by itbgtk09

2021-04-22 10:06 UTC, dzianis-chaika requested changes

2021-04-22 10:06 UTC, dzianis-chaika commented on scripts/script.js
> +const typeCarItem = document.querySelectorAll('#typeCarItem');
Как писал выше, в typeCarItem должен вернуться один элемент. Лучше для таких целей использовать классы или свои собственные атрибуты, например, `<div js-car-item></div>` и `const typeCarItem = document.querySelectorAll('div[js-car-item]');`

2021-04-22 11:05 UTC, DenisKalyanov requested changes

2021-04-22 11:05 UTC, DenisKalyanov commented on index.html
> +            <li class="car-slider-dots__item" id="carSliderDotsItem" data-dots-number="2"></li>
Слайды переключаться не будут.

2021-04-22 12:59 UTC, itbgtk09 commented on index.html
> +            <li class="car-slider-dots__item" id="carSliderDotsItem" data-dots-number="2"></li>
Это точки, которые подсвечивают, какой сейчас выбран слайд, просто точка(черная), текущая (черная в желтом кружочке)

2021-04-22 13:00 UTC, itbgtk09 commented on scripts/script.js
> +        positionSliderTrack = +item.dataset.slideNumber * 100
нет, это приведение к типу number

2021-04-22 14:00 UTC, DenisKalyanov commented on scripts/script.js
> +        positionSliderTrack = +item.dataset.slideNumber * 100
Тогда стоит почитать про Преобразование типов, в данном случае унарный плюс не требуется.

2021-04-22 14:01 UTC, DenisKalyanov commented on index.html
> +            <li class="car-slider-dots__item" id="carSliderDotsItem" data-dots-number="2"></li>
Так а что, мы не сможем нажать на точечку и поменять слайд :"(

2021-04-23 17:40 UTC, DenisKalyanov approved these changes

2021-04-23 17:40 UTC, DenisKalyanov approved these changes

2021-04-23 17:41 UTC, merged